import { useState, useEffect, useRef } from 'react';
import { Search, ArrowUp, X } from 'lucide-react';
import imgImage39 from '@/assets/f2078903bc60d007ab38f14e8f06bb0ac47cb5a0.png';

// Section structure
interface Section {
  id: string;
  title: string;
  content: string[];
}

interface TermsAndPoliciesProps {
  onClose: () => void;
}

const sections: Section[] = [
  {
    id: 'introduction',
    title: 'Introduction',
    content: [
      'Makeen is a web-based platform that helps users upload tabular datasets (Excel/CSV) to generate predictions and explanations using Explainable AI methods. These Terms & Policies explain the rules for using the platform and how we handle content and data.',
    ],
  },
  {
    id: 'eligibility-accounts',
    title: 'Eligibility & Accounts',
    content: [
      'You must use the platform through a registered account.',
      'You are responsible for maintaining the confidentiality of your account credentials.',
      'If you suspect unauthorized access, please update your password and notify us.',
    ],
  },
  {
    id: 'using-platform',
    title: 'Using the Platform',
    content: [
      'The platform is designed to support:',
      '• Uploading Excel/CSV files',
      '• Asking questions or instructions in natural language',
      '• Generating predictions from uploaded data',
      '• Viewing explanations for results (Explainable AI)',
      '• Exporting results',
      '• Providing feedback on explanation clarity',
      'You agree to use the platform only for lawful purposes and in a way that does not harm the system or other users.',
    ],
  },
  {
    id: 'uploaded-data',
    title: 'Uploaded Data & User Content',
    content: [
      'You retain ownership of the files and data you upload.',
      'You confirm that you have the right to upload and use the data you provide.',
      'Do not upload sensitive personal data unless you have explicit permission and a lawful basis to do so.',
      'You are responsible for verifying that uploaded data is appropriate for your intended use.',
    ],
  },
  {
    id: 'predictions-explanations',
    title: 'Predictions & Explanations (Important Notice)',
    content: [
      'Predictions and explanations are generated by machine learning models and XAI methods (such as SHAP and LIME).',
      'Outputs are provided to help interpretation and understanding, but they may contain inaccuracies.',
      'You should not rely on platform outputs as the sole basis for critical decisions (medical, legal, financial, or safety-related decisions).',
    ],
  },
  {
    id: 'privacy-summary',
    title: 'Privacy Summary',
    content: [
      'We aim to minimize data exposure and use uploaded data only to process your request and show results inside the platform.',
      'Full privacy details:',
      '• What data we collect',
      '• How we use it',
      '• How long we keep it (TODO: add retention period if defined by the team)',
    ],
  },
  {
    id: 'acceptable-use',
    title: 'Acceptable Use',
    content: [
      'You agree not to:',
      '• Upload content you do not have rights to use',
      '• Attempt to bypass security or access other users\' data',
      '• Introduce malware or harmful code',
      '• Use the platform to generate or support illegal activity',
      '• Overload the system intentionally (abuse, spam, automated scraping)',
    ],
  },
  {
    id: 'intellectual-property',
    title: 'Intellectual Property',
    content: [
      'The platform\'s interface, branding, and system design belong to the Makeen project team.',
      'You may not copy, reverse engineer, or redistribute the platform without permission.',
    ],
  },
  {
    id: 'service-availability',
    title: 'Service Availability',
    content: [
      'The platform is an MVP for academic purposes and may change over time.',
      'We do not guarantee uninterrupted availability.',
      'We may update, modify, or suspend features to improve the system.',
    ],
  },
  {
    id: 'exports-downloads',
    title: 'Exports & Downloads',
    content: [
      'Export features allow you to download results (e.g., PDF/Excel/HTML).',
      'You are responsible for how you store, share, or use exported files.',
    ],
  },
  {
    id: 'subscriptions-plans',
    title: 'Subscriptions & Plans',
    content: [
      'This section outlines the policies related to subscription plans, pricing tiers, and future paid features on the Makeen platform.',
      '',
      '1. Current Availability of Subscriptions',
      'At this stage, all subscription plans displayed on the platform are part of a future roadmap. No paid subscriptions are currently active, and users can access the platform under the free plan.',
      '',
      '2. Future Paid Plans',
      'Makeen may introduce paid subscription plans in future versions. These plans may include additional features, higher usage limits, or enterprise-level services. Details such as pricing and availability are subject to change.',
      '',
      '3. No Automatic Charges',
      'Users will not be charged automatically, and no payment information is collected or stored at this time.',
      '',
      '4. Feature Changes & Availability',
      'Features listed under specific plans may be modified, relocated between plans, or discontinued as the platform evolves.',
      '',
      '5. Data & Plan Transitions',
      'When subscription plans are introduced, Makeen aims to ensure that users can transition between plans without losing their existing data or history, subject to technical limitations.',
      '',
      '6. Enterprise & Custom Plans',
      'Enterprise or custom plans may be offered to organizations with specific requirements, including advanced support, customization, or deployment options.',
      '',
      '7. Updates to Subscription Policies',
      'Makeen reserves the right to update subscription-related policies at any time. Any significant changes will be communicated through the platform.',
    ],
  },
  {
    id: 'termination',
    title: 'Termination',
    content: [
      'We may suspend or restrict access if:',
      '• You violate these Terms',
      '• Your use risks platform security or stability',
      'You may stop using the platform at any time.',
    ],
  },
  {
    id: 'changes',
    title: 'Changes to These Terms',
    content: [
      'We may update these Terms & Policies to reflect improvements or changes in features. The "Last updated" date will be revised accordingly.',
    ],
  },
  {
    id: 'contact',
    title: 'Contact',
    content: [
      'For help, questions, or concerns:',
      'Email: TODO (add official support email)',
      'You can also use "Help Center" and "Report Bug" inside the platform.',
    ],
  },
];

export function TermsAndPolicies({ onClose }: TermsAndPoliciesProps) {
  const [activeSection, setActiveSection] = useState<string>('introduction');
  const [showBackToTop, setShowBackToTop] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [isTOCOpen, setIsTOCOpen] = useState(false);
  const sectionRefs = useRef<{ [key: string]: HTMLElement | null }>({});
  const observerRef = useRef<IntersectionObserver | null>(null);
  const scrollContainerRef = useRef<HTMLDivElement>(null);

  // Filter sections based on search
  const filteredSections = sections.filter((section) =>
    section.title.toLowerCase().includes(searchQuery.toLowerCase())
  );

  // Scroll to section
  const scrollToSection = (sectionId: string) => {
    const element = sectionRefs.current[sectionId];
    const container = scrollContainerRef.current;
    
    if (element && container) {
      const elementTop = element.offsetTop;
      const offset = 100; // Offset for fixed header
      
      container.scrollTo({
        top: elementTop - offset,
        behavior: 'smooth',
      });

      // Close mobile TOC
      setIsTOCOpen(false);
    }
  };

  // Scroll to top
  const scrollToTop = () => {
    const container = scrollContainerRef.current;
    if (container) {
      container.scrollTo({
        top: 0,
        behavior: 'smooth',
      });
    }
  };

  // Track scroll position for back-to-top button (show after ~30% scroll)
  useEffect(() => {
    const container = scrollContainerRef.current;
    if (!container) return;

    const handleScroll = () => {
      const scrollPercentage =
        (container.scrollTop / (container.scrollHeight - container.clientHeight)) * 100;
      setShowBackToTop(scrollPercentage > 30);
    };

    container.addEventListener('scroll', handleScroll);
    return () => container.removeEventListener('scroll', handleScroll);
  }, []);

  // Intersection observer for active section
  useEffect(() => {
    const container = scrollContainerRef.current;
    if (!container) return;

    observerRef.current = new IntersectionObserver(
      (entries) => {
        // Find the most visible section
        const visibleEntries = entries.filter((entry) => entry.isIntersecting);
        
        if (visibleEntries.length > 0) {
          // Choose the section with the highest intersection ratio
          const mostVisible = visibleEntries.reduce((prev, current) =>
            current.intersectionRatio > prev.intersectionRatio ? current : prev
          );
          setActiveSection(mostVisible.target.id);
        }
      },
      {
        root: container,
        rootMargin: '-100px 0px -50% 0px',
        threshold: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
      }
    );

    // Observe all sections
    Object.values(sectionRefs.current).forEach((section) => {
      if (section) {
        observerRef.current?.observe(section);
      }
    });

    return () => {
      observerRef.current?.disconnect();
    };
  }, []);

  // Handle Esc key to close
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        onClose();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [onClose]);

  return (
    <div ref={scrollContainerRef} className="fixed inset-0 bg-[#1a1a1a] z-[100] overflow-y-auto">
      {/* Subtle gradient background */}
      <div
        className="fixed inset-0 opacity-[0.08] pointer-events-none"
        style={{
          background:
            'radial-gradient(circle at 20% 10%, #FFC107 0%, transparent 40%), radial-gradient(circle at 80% 30%, #E59866 0%, transparent 50%)',
        }}
      />

      {/* Top bar */}
      <div className="sticky top-0 z-40 bg-[#1a1a1a]/95 backdrop-blur-md border-b border-[rgba(255,252,254,0.1)]">
        <div className="max-w-[1400px] mx-auto px-[24px] py-[16px] flex items-center justify-between">
          {/* Logo */}
          <div className="flex items-center gap-[12px]">
            <div className="w-[56px] h-[56px] rounded-[6px] overflow-hidden">
              <img
                alt="Makeen Logo"
                className="w-full h-full object-cover"
                src={imgImage39}
              />
            </div>
            <span className="font-['Roboto:SemiBold',sans-serif] text-[24px] text-[#fffcfe]">
              Makeen
            </span>
          </div>

          {/* Close X button */}
          <button
            onClick={onClose}
            className="w-[40px] h-[40px] flex items-center justify-center rounded-[8px] hover:bg-[#2c2c2c] transition-colors"
            aria-label="Close terms and policies"
          >
            <X className="w-[20px] h-[20px] text-[#999] hover:text-[#fffcfe] transition-colors" />
          </button>
        </div>
      </div>

      {/* Hero header */}
      <div className="max-w-[1400px] mx-auto px-[24px] pt-[60px] pb-[40px]">
        <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-[16px] mb-[12px]">
          <div>
            <h1 className="font-['Roboto:Bold',sans-serif] text-[42px] md:text-[52px] text-[#fffcfe] mb-[12px] relative inline-block">
              Terms & Policies
              <div className="absolute bottom-[-4px] left-0 right-0 h-[3px] bg-gradient-to-r from-[#7760bd] to-[#9580d4] rounded-full" />
            </h1>
            <p className="font-['Roboto:Regular',sans-serif] text-[16px] text-[#999] mt-[20px]">
              Transparent policies designed to keep your data safe and your experience clear.
            </p>
          </div>
          <div className="flex-shrink-0">
            <p className="font-['Roboto:Regular',sans-serif] text-[14px] text-[#666]">
              Last updated: <span className="text-[#999]">February 1, 2026</span>
            </p>
          </div>
        </div>
      </div>

      {/* Main content area */}
      <div className="max-w-[1200px] mx-auto px-[24px] pb-[80px]">
        <div className="grid grid-cols-1 lg:grid-cols-[280px_1fr] gap-[32px]">
          {/* Left: Table of Contents (Desktop - Sticky) */}
          <div className="hidden lg:block">
            <div className="sticky top-[100px]">
              <div className="bg-[#1e1e1e] border border-[rgba(255,252,254,0.1)] rounded-[12px] p-[20px] shadow-[0_2px_8px_rgba(0,0,0,0.3)]">
                <h2 className="font-['Roboto:SemiBold',sans-serif] text-[16px] text-[#fffcfe] mb-[16px]">
                  On this page
                </h2>

                {/* Search TOC */}
                <div className="relative mb-[16px] group/search">
                  {/* Sharp gradient border */}
                  <div
                    className="absolute inset-[-2px] rounded-[10px] opacity-0 group-focus-within/search:opacity-60 transition-opacity duration-[180ms] pointer-events-none"
                    style={{
                      background: '#7760bd',
                      padding: '2px',
                    }}
                  >
                    <div className="h-full w-full bg-transparent rounded-[8px]"></div>
                  </div>

                  {/* Blurred glow */}
                  <div
                    className="absolute inset-[-3px] rounded-[11px] opacity-0 group-focus-within/search:opacity-25 transition-opacity duration-[180ms] pointer-events-none"
                    style={{
                      background:
                        'linear-gradient(135deg, #7760bd 0%, #9580d4 25%, #FFC107 50%, #E59866 75%, #7760bd 100%)',
                      filter: 'blur(18px)',
                    }}
                  />

                  <div className="relative">
                    <Search className="absolute left-[12px] top-1/2 -translate-y-1/2 w-[16px] h-[16px] text-[#666] z-10" />
                    <input
                      type="text"
                      value={searchQuery}
                      onChange={(e) => setSearchQuery(e.target.value)}
                      placeholder="Search in this page…"
                      className="w-full bg-[#2c2c2c] border border-[rgba(255,252,254,0.1)] rounded-[8px] pl-[36px] pr-[12px] py-[8px] font-['Roboto:Regular',sans-serif] text-[13px] text-[#fffcfe] placeholder:text-[#666] focus:outline-none focus:border-[#7760bd] transition-all relative z-[1]"
                    />
                  </div>
                </div>

                {/* TOC Links */}
                <nav className="space-y-[4px]" role="navigation" aria-label="Table of contents">
                  {filteredSections.length > 0 ? (
                    filteredSections.map((section) => (
                      <button
                        key={section.id}
                        onClick={() => scrollToSection(section.id)}
                        aria-current={activeSection === section.id ? 'true' : undefined}
                        className={`w-full text-left px-[12px] py-[8px] rounded-[6px] font-['Roboto:Regular',sans-serif] text-[14px] transition-all cursor-pointer ${
                          activeSection === section.id
                            ? 'bg-[#7760bd]/20 text-[#7760bd] border-l-2 border-[#7760bd]'
                            : 'text-[#999] hover:bg-[#2c2c2c] hover:text-[#fffcfe]'
                        }`}
                      >
                        {section.title}
                      </button>
                    ))
                  ) : (
                    <p className="px-[12px] py-[8px] font-['Roboto:Regular',sans-serif] text-[13px] text-[#666] italic">
                      No matching sections.
                    </p>
                  )}
                </nav>
              </div>
            </div>
          </div>

          {/* Mobile TOC Dropdown */}
          <div className="lg:hidden mb-[24px]">
            <button
              onClick={() => setIsTOCOpen(!isTOCOpen)}
              className="w-full bg-[#1e1e1e] border border-[rgba(255,252,254,0.1)] rounded-[12px] px-[20px] py-[16px] flex items-center justify-between"
            >
              <span className="font-['Roboto:SemiBold',sans-serif] text-[16px] text-[#fffcfe]">
                On this page
              </span>
              <svg
                className={`w-[20px] h-[20px] text-[#999] transition-transform ${
                  isTOCOpen ? 'rotate-180' : ''
                }`}
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
              </svg>
            </button>

            {isTOCOpen && (
              <div className="mt-[8px] bg-[#1e1e1e] border border-[rgba(255,252,254,0.1)] rounded-[12px] p-[16px] shadow-[0_2px_8px_rgba(0,0,0,0.3)]">
                <nav className="space-y-[4px]">
                  {sections.map((section) => (
                    <button
                      key={section.id}
                      onClick={() => scrollToSection(section.id)}
                      className={`w-full text-left px-[12px] py-[8px] rounded-[6px] font-['Roboto:Regular',sans-serif] text-[14px] transition-all cursor-pointer ${
                        activeSection === section.id
                          ? 'bg-[#7760bd]/20 text-[#7760bd] border-l-2 border-[#7760bd]'
                          : 'text-[#999] hover:bg-[#2c2c2c] hover:text-[#fffcfe]'
                      }`}
                    >
                      {section.title}
                    </button>
                  ))}
                </nav>
              </div>
            )}
          </div>

          {/* Right: Main document */}
          <div className="lg:col-start-2">
            <div className="bg-[#1e1e1e] border border-[rgba(255,252,254,0.1)] rounded-[12px] p-[32px] md:p-[48px] shadow-[0_2px_8px_rgba(0,0,0,0.3)]">
              {sections.map((section, index) => (
                <section
                  key={section.id}
                  id={section.id}
                  ref={(el) => (sectionRefs.current[section.id] = el)}
                  className={index !== 0 ? 'mt-[48px]' : ''}
                >
                  <h2 className="font-['Roboto:SemiBold',sans-serif] text-[24px] text-[#fffcfe] mb-[16px]">
                    {section.title}
                  </h2>

                  <div className="space-y-[16px]">
                    {section.content.map((paragraph, pIndex) => (
                      <p
                        key={pIndex}
                        className="font-['Roboto:Regular',sans-serif] text-[15px] text-[#999] leading-[1.7]"
                      >
                        {paragraph}
                      </p>
                    ))}
                  </div>

                  {index !== sections.length - 1 && (
                    <div className="mt-[32px] h-[1px] bg-[rgba(255,252,254,0.1)]" />
                  )}
                </section>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Back to top button */}
      {showBackToTop && (
        <button
          onClick={scrollToTop}
          className="fixed bottom-[32px] right-[32px] bg-[#7760bd] hover:bg-[#8870cd] text-white rounded-[12px] px-[20px] py-[12px] flex items-center gap-[8px] shadow-[0_4px_16px_rgba(119,96,189,0.4)] transition-all z-50 group"
        >
          <ArrowUp className="w-[18px] h-[18px]" />
          <span className="font-['Roboto:Medium',sans-serif] text-[14px]">Back to top</span>
        </button>
      )}

      {/* Footer */}
      <footer className="border-t border-[rgba(255,252,254,0.1)] bg-[#1a1a1a]">
        <div className="max-w-[1400px] mx-auto px-[24px] py-[24px]">
          <div className="flex flex-col md:flex-row items-center justify-center md:justify-between gap-[16px]">
            <p className="font-['Roboto:Regular',sans-serif] text-[14px] text-[#666]">
              Copyright © 2026 Makeen | All Rights Reserved
            </p>
            <div className="flex items-center gap-[24px]">
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}